bellshade/CPP

sorting/CmakeLists.txt
sorting/bubblesort.cpp

Penambahan algoritma bubblesort 
- ``os`` = `` macOS``
- ``g++`` = ``Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.28)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin``

add: bubblesort algorithm

---

README.md
basic/3_operator/README.md
basic/4_conditional/README.md
basic/README.md

- ``os`` = ``linux / windows / macOS``

add: operator dan conditional

---

basic/5_looping/README.md
basic/README.md

- ``os`` = ``linux / windows / macOS``

add: for loop

---

basic/3_operator/README.md

Memperbaiki README pada tabel operator logika OR yang terbaca sebagai column dengan menambahkan backslash
- ``os`` = ``linux / windows / macOS``

docs: Memperbaiki tabel operator logika OR

---

README.md

- ``os`` = ``linux / windows / macOS``

feat: README reformatting + roadmap

---

basic/9_multidimensional_array/README.md
basic/9_multidimensional_array/multidimensional_array.cpp

feat: menambahkan multidimensional array

---

README.md

docs: mengubah ulr discord

---

struktur_data/README.md

Saya menambahkan materi general mengenai struktur data dalam bentuk `README.md` di folder "struktur_data"
- ``os`` = ``windows``
- ``g++`` = ``11.2.0``

feat: menambahkan materi umum struktur data

---

algorithm/sorting/bubblesort_doubly_linkedlist.cpp

Memberikan contoh sorting data doubly linked list dengan algoritma bubble sort.
- ``g++`` = 12.2.0
Issues : #60 
Label HACKTOBERFEST-ACCEPTED

add: algoritma bubble sort pada doubly linked list

---

README.md

Saya menambahkan kembali vistor badge karna sebelumnya error pada server.
- ``OS`` = `Android` 
- ``g++`` = 
Issues : #

docs: menambahkan kembali visitor badge

---

.github/workflows/cpp.yml
.github/workflows/format_nama_file.sh
math/fibonacci.cpp

Memperbaiki logic pada base condition `fibonacci()`
Menambahkan 2 test case pada `test()`
Dan Menambahkan Deskripsi untuk user input (stdin)
- ``g++`` = 9.4.0 
Issues : #

Fix math/fibonacci

---

math/CMakeLists.txt
math/cek_faktorial.cpp

menambahkan contoh sederhana mengecek angka faktorial
- ``OS`` = `Mac OS` 
- ``g++`` = ``gcc 12.2`` 
Issues : #

feat: menambahkan contoh  sederhana mengecek faktorial

---

algorithm/algoritma_greedy/huffman.cpp
algorithm/algoritma_greedy/knapsack.cpp

menambaahkan contoh dari algoritma greedy yaitu
- problem knapsack yang solusinya menggunaakan algoritma greedy
- contoh sederhana dari kode huffman
- ``OS`` = `linux` 
- ``g++`` = ``12.2.1``

feat: menambahkan contoh dari algoritma greedy

---

math/fibonacci.cpp

mempersingkat statement logika pada fibonnaci dan menutup issue #64 dan melanjutkan pull request dari #72

fix: mempersingkat statement logika

---

algorithm/sorting/snail_sort.cpp

- ``g++`` = `12.2.1`
Issues : #

feat: menambahkan solusi untuk `snail sort`

---

algorithm/sorting/bucket_sort.cpp

bucket sort adalah algoritma sorting yang mendistribusikan elemen dari array ke dalam sebuah bentuk ember. setiap ember kemudian diurutkan satu per satu, baik menggunakan algoritma pengurutan yagn berbeda atau dengan menerapkan algoritma pengurutan bucket secara rekursif
referensi dari bucket sort:
- [wikipedia - bucket sort](https://en.wikipedia.org/wiki/Bucket_sort)
- [programiz - bucket sort algorithm](https://www.programiz.com/dsa/bucket-sort)
- [simplelearn - bucket sort algorithm: overview, time complexity & pseudocode](https://www.simplilearn.com/tutorials/data-structure-tutorial/bucket-sort-algorithm)
- ``g++`` = ``12.2.1``

feat: menambahkan contoh sederhana dari bucket sorting

---

math/cek_prima.cpp

bilangan prima adalah bilangan asli lebih dari 1 yang bukan hasilkali dari dua bilangan asli yang lebih kecil. Bilangan asli yang lebih dari 1 dan bukan bilangan prima disebut bilangan komposit.
- ``g++`` = ``12.2.1.20230201``

feat: menambahkan contoh dari cek bilangan prima

---

readme.md

docs: memperbaiki link kosong pada documentation close #54

---

math/rabin_miller.cpp

menambahkan algoritma rabin miller untuk cek probabilitas cenderungnya sebuah angka itu adalah bilangan prima
- ``g++`` = `12.2.1`

feat: menambahkan rabin miller algorithm

---

math/variance.cpp

- ``g++`` = g++ (Ubuntu 12.2.0-3ubuntu1) 12.2.0
Issues : #

feat: menambahkan algorithma variance

---

math/relu.cpp

- ``g++`` = g++ (Ubuntu 12.2.0-3ubuntu1) 12.2.0
Issues : #

feat: menambahkan algoritma relu

---

math/quadratic_formula.cpp

- ``OS`` = `Linux`
- ``g++`` = g++ (Ubuntu 12.2.0-3ubuntu1) 12.2.0
Issues : #

feat: menambahkan formula quadratic formula

---

math/radian.cpp

- ``OS`` = `Ubuntu Linux` 
- ``g++`` = `g++ (Ubuntu 12.2.0-3ubuntu1) 12.2.0`
Issues : #

feat: menambahkan radians

---

math/volume.cpp

- ``g++`` = `g++ (Ubuntu 12.2.0-3ubuntu1) 12.2.0`
Issues : #

feat: menambahkan fungsi volume

---

algorithm/sorting/selection_sort.cpp

Saya menambahkan implementasi algoritma **Selection Sort** menggunakan **vector** sebagai alternatif dari array. Algoritma ini memanfaatkan referencing untuk menghindari penyalinan data yang tidak perlu, dan disertai dokumentasi serta komentar kode yang menjelaskan setiap langkah dengan detail.
---
---
- ``g++`` = 
---

add:selection sort

---

.github/workflows/cpp.yml
.linter/file_linter.py

improvisasi workflow dengan membuat script linter cpp ke file `.linter`
- ``g++`` = ``14.2.1 20240910``

chore: improvisasi unittesting workflow

---

.gitattributes
.github/ISSUE_TEMPLATE/bug_report.md
CODE_OF_CONDUCT.md
readme.md

tambahan lainnya:
- penambahan gitattributes
- bug report issue template
- menghapus badge di README.md

chore: menambahkan code conduct dll

---

math/sigmoid.cpp

Saya menambahkan file baru bernama `sigmoid.cpp` di dalam folder `math`. File ini berisi implementasi fungsi **sigmoid** yang merupakan salah satu fungsi aktivasi penting dalam Machine Learning dan Deep Learning. Fungsi ini berfungsi untuk mengonversi input numerik menjadi nilai antara 0 hingga 1, yang sering digunakan dalam masalah klasifikasi biner.
- ``g++`` =  11.4.0

add:sigmoid.cpp

---

.mergify.yml

konfigurasi mergify untuk co authored bellshade bot dan juga tambah label untuk mengikuti konfigurasi default dari tiap repositori bellshade

chore: update konfigurasi mergify

---

CMakeLists.txt
geometri/CMakeLists.txt
geometri/graham_scan.cpp
geometri/include/fungsi_graham.hpp

membuat algoritma untuk membuat metode menemukan convex hull dari sekumpulan titik di bidang
- ``g++`` = `14.2.1 20240910`

feat: menambahkan algoritma graham scan

---

basic/04_operator/operator_bitwise.cpp
basic/04_operator/readme.md
basic/08_string/menggunakan_array.cpp

- ``g++`` = `11.4.0` 
Issues : #

feat:menambahkan operator bitwise pada basic operator

---

algorithm/sorting/bubblesort.cpp
backtracking/wildcard_matching.cpp

- bubblesort
- pakai konsep early exit, jika dalam satu iterasi tidak ada swapping
- ubah swapping pakai std::swap karena lebih efisien
- pakai const untuk konstant di `tampilkanUrutan`
- wildcard_matching
- pakai `int8_t` untuk dp table sehingga lebih hemat memori
- std::function() untuk lambda function yang rekursif
- menghindari pembuatan copy string pada tiap pemanggilan function
- ``g++`` = `15.1.1 20250425` 
Issues : #

chore: update performance issue

---

struktur_data/array/array.cpp
struktur_data/array/dynamic_array/array_dinamis.cpp
struktur_data/array/readme.md

Menambahkan Materi Array
Struktur yang ditambahkan:
struktur_data/Array
```bash
├── array.cpp
├── dynamic_array
│   ├── array_dinamis.cpp
│   └── readme.md
└── readme.md
1 directory, 4 files
```
---
- Membuat direktori baru khusus untuk topik **Array** sebagai bagian dari materi dasar struktur data.
- Implementasi array statis **tanpa menggunakan STL**.
- Fitur:
- Penyisipan elemen manual menggunakan loop.
- Pemantauan kapasitas dan ukuran dengan struct `DetailArray`.
- Validasi kapasitas saat insert.
- Cocok untuk memperkuat pemahaman dasar array manual.
- Materi yang dijelaskan:
- Konsep array statis.
- Cara deklarasi dan inisialisasi sebagian.
- Input data menggunakan loop.
- Perbedaan antara nilai default dan garbage value dalam array.
- Disediakan juga:
- Contoh kode C++.
- …

Feat:Menambahkan materi Array

---

algorithm/bit_manipulation/lsb.cpp

Menambahkan materi `Least Significat Bit(LSB)`
1. **Implementasi fungsi `lsb(int n)`**
- Fungsi menghitung nilai bit paling kanan menggunakan operasi bitwise AND: `n & 1`.
- Fungsi ini mengembalikan 0 atau 1 tergantung dari nilai LSB pada bilangan `n`.
- Penambahan komentar biner sebagai ilustrasi perhitungan.
2. **Implementasi fungsi utama `main()`**
- Menerima input bilangan `n` dari pengguna.
- Menampilkan nilai LSB.
- Menggunakan hasil LSB untuk menentukan apakah `n` adalah bilangan ganjil atau genap.
---
- [ x] Saya menambah algoritma terbaru.
- [ x] Saya menambah dokumentasi.
- [x ] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/CPP/blob/main/CONTRIBUTING.md) dan sudah menyetujui semua syarat.
- [ x] Saya telah menambahkan komentar kode yang memberikan …

Feat:Menambahkan materi lsb

---

algorithm/bit_manipulation/msb.cpp

Menambahkan materi Most Significat Bit(Bit)
1. **Implementasi fungsi `msb(int n)`**
- Menghitung posisi MSB secara manual menggunakan operasi pergeseran bit (`>>`).
- Fungsi ini tidak menggunakan logaritma atau fungsi bawaan, cocok untuk dipahami secara konseptual.
2. **Implementasi fungsi `best_practices(int n)`**
- Menggunakan built-in GCC `__builtin_clz` untuk menghitung jumlah nol di depan (leading zeros).
- Sangat efisien dan optimal untuk produksi/performa tinggi.
3. **Contoh Penggunaan**
- Program menerima input `n`, mencetak posisi MSB, dan nilai pangkat dua terdekat atau sama dengan `n`.
---
- [ x] Saya menambah algoritma terbaru.
- [ x] Saya menambah dokumentasi.
- [x ] Saya sudah membaca (I have read) [CONTRIBUTING](https://github.com/bellshade/CPP/blob/main/CONTRIBUTING.md) …

Fix:menambahkan materi msb

---

algorithm/sorting/insertion_sort.cpp
algorithm/sorting/selection_sort.cpp

Saya melakukan perbaikan dan penambahan dokumentasi pada dua file dalam direktori `algorithm/sorting/`, yaitu:
- `selection_sort.cpp`
- `insertion_sort.cpp`
---
- Memperbaiki logika pemilihan elemen minimum pada algoritma Selection Sort.
- Membersihkan struktur kode agar lebih konsisten dan terbaca.
- Menambahkan komentar dan dokumentasi untuk tiap fungsi, menjelaskan peran dan cara kerjanya.
- Memperbaiki cara penulisan dan pengorganisasian input/output agar lebih rapi di terminal.
- Menghilangkan penggunaan header yang tidak diperlukan (`<array>`).
---
- Mengubah struktur parameter fungsi untuk efisiensi dan modularitas.
- Menambahkan dua fungsi sorting terpisah: ascending dan descending.
- Menambahkan dokumentasi pada setiap fungsi, termasuk penjelasan logika sorting.
- Menyusun ulang …

docs: menambahkan dokumentasi format doxygen

---

struktur_data/hash_table/hash_function/multiplication_method.cpp

`multiplication method` adalah salah satu hash function yang digunakan untuk memetakan value pada hash table,walaupun penggunaanya tidak umum pada `hash table`
1.**Membuat direktori baru**
```bash
├── asset
│   ├── hash_table_chaining.png
│   ├── hash_table_collision.png
│   ├── hash_table_visualisasi.png
│   └── tabel_hash_kode_demo.png
├── hash_function
│   └── multiplication_method.cpp
├── hash_table.cpp
└── readme.md
```
Menambahkan dir `hash_function` berisi program hash function yang dipakai pada hash table
2.**Menambahkan program division method**
contoh output:
```bash
load factor saat ini: 0.125
load factor saat ini: 0.25
load factor saat ini: 0.375
load factor saat ini: 0.5
load factor saat ini: 0.625
0:5 -> nullptr 
1:2 -> nullptr 
2:7 -> nullptr 
3:nullptr 
4:nullptr 
5:6 -> …
```

feat: implement multiplication method hash
